"""
report_pdf.py
-------------
Generates a digital compliance report (PDF) for a single scan, suitable
for attaching to an enforcement file.
"""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, Image as RLImage)

STATUS_COLORS = {
    "PASS": colors.HexColor("#1a7f37"),
    "FAIL": colors.HexColor("#c0392b"),
    "REVIEW": colors.HexColor("#b8860b"),
}


def build_pdf(scan: dict, declarations: list, image_path: str | None = None) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], fontSize=16)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=9, textColor=colors.grey)

    story = []
    story.append(Paragraph("Legal Metrology Compliance Report", title_style))
    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011", small))
    story.append(Spacer(1, 8))

    meta_rows = [
        ["Product", scan.get("product_name") or "—"],
        ["Brand", scan.get("brand") or "—"],
        ["Category", scan.get("category") or "—"],
        ["Scan ID", str(scan.get("id", "—"))],
        ["Scanned by", scan.get("scanned_by") or "—"],
        ["Location", scan.get("location") or "—"],
        ["Date", scan.get("created_at", "—")],
        ["Overall status", scan.get("overall_status", "—")],
        ["Compliance score", f"{scan.get('score', 0)}%"],
    ]
    meta_table = Table(meta_rows, colWidths=[110, 360])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#555555")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#e0e0e0")),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 12))

    if image_path:
        try:
            story.append(RLImage(image_path, width=140, height=140, kind="proportional"))
            story.append(Spacer(1, 12))
        except Exception:
            pass

    story.append(Paragraph("Declaration-by-declaration findings", styles["Heading2"]))

    cell_style = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=8.5, leading=11)
    header_style = ParagraphStyle("CellHeader", parent=cell_style, textColor=colors.white, fontName="Helvetica-Bold")

    def cell(text, header=False):
        return Paragraph(str(text).replace("\n", "<br/>"), header_style if header else cell_style)

    def status_cell(status):
        style = ParagraphStyle("StatusCell", parent=cell_style, textColor=STATUS_COLORS.get(status, colors.black),
                                fontName="Helvetica-Bold")
        return Paragraph(status, style)

    data = [[cell("Declaration", True), cell("Rule reference", True), cell("Status", True), cell("Detail", True)]]
    for d in declarations:
        data.append([cell(d["label"]), cell(d["rule_ref"]), status_cell(d["status"]), cell(d["detail"])])
    tbl = Table(data, colWidths=[118, 82, 48, 202], repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2933")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#dddddd")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]
    tbl.setStyle(TableStyle(style_cmds))
    story.append(tbl)
    story.append(Spacer(1, 14))

    violations = [d for d in declarations if d["status"] == "FAIL"]
    if violations:
        story.append(Paragraph("Violation summary", styles["Heading2"]))
        for v in violations:
            story.append(Paragraph(f"• <b>{v['label']}</b> ({v['rule_ref']}): {v['detail']}", styles["Normal"]))
        story.append(Spacer(1, 10))

    story.append(Paragraph(
        "This report is generated by an automated OCR + rule-based screening system and is "
        "intended to support, not replace, inspection by an authorised Legal Metrology officer. "
        "Declarations marked REVIEW require manual confirmation.", small))

    doc.build(story)
    return buf.getvalue()
